version: "3"

services:
  frontend:
    build: ./frontend/docker
    ports:
      - "4200:4200"
    volumes:
      - "./frontend/server:/projects"
    tty: true
  db:
    image: mysql:5.7
    container_name: docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaigan_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./kaigan/db/data:/var/lib/mysql
      - ./kaigan/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./kaigan/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 4306:3306
