version: "3"

services:
  frontend:
    build: ./frontend/docker
    ports:
      - "4200:4200"
    volumes:
      - "./frontend/server:/projects"
    tty: true
  backend:
    build: ./backend/docker/node
    ports:
      - "3000:3000"
    volumes:
      - "./backend/"
    tty: true
